
-- IS_BLOG_DB TABLE QUERY

CREATE TABLE TBL_USER(
	USER_ID VARCHAR(20) CONSTRAINT PK_TBL_USER PRIMARY KEY,
	USER_NM VARCHAR(10) NOT NULL,
	USER_PWD VARCHAR(500) NOT NULL,
	CRE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	IS_USE VARCHAR(2) NOT NULL DEFAULT 'Y'
);

ALTER TABLE TBL_USER ADD CONSTRAINT CHK_IS_USE CHECK (IS_USE IN('Y','N') );

CREATE TABLE TBL_AUTH(
	AUTH_ID VARCHAR(50) CONSTRAINT PK_TBL_AUTH PRIMARY KEY,
	AUTH_NM VARCHAR(20) NOT NULL
);

CREATE TABLE TBL_USER_AUTH (
	AUTH_ID VARCHAR(50) NOT NULL,
	USER_ID VARCHAR(20) NOT NULL,
	CONSTRAINT FK_TBL_AUTH_ID FOREIGN KEY (AUTH_ID) REFERENCES TBL_AUTH(AUTH_ID),
	CONSTRAINT FK_TBL_USER_ID FOREIGN KEY (USER_ID) REFERENCES TBL_USER(USER_ID)
);

-- 더미데이터
INSERT INTO TBL_USER VALUES('AAA','테스트','123456789',DEFAULT,DEFAULT);
INSERT INTO TBL_AUTH VALUES('T_AUTH_VAL','TEST');
INSERT INTO TBL_USER_AUTH VALUES('T_AUTH_VAL', 'AAA');


SELECT * FROM TBL_USER;
SELECT * FROM TBL_AUTH;
SELECT * FROM TBL_USER_AUTH;



